on:
  push:
    branches:
      - main
      - fix-ci
  pull_request:
    branches:
      - main

name: test

jobs:
  build-xelatex:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: "latexmk -xelatex -interaction=nonstopmode -file-line-error -halt-on-error -shell-escape main"
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: document output
          path: main.pdf

  build-lualatex:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: "latexmk -lualatex -interaction=nonstopmode -file-line-error -halt-on-error -shell-escape main"
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: document output
          path: main.pdf